<a href="https://colab.research.google.com/github/Dhonald229/Projet-colab/blob/main/Etude_d'actif_financier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Projet D'étude d'investissement**

In [ ]:
import pandas as pd

In [ ]:
import yfinance as yf

In [ ]:
prix=yf.Ticker("AAPL").history(period="5y")
prix

,Close,High,Low,Open,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-05-07 00:00:00-04:00,NaN,NaN,NaN,NaN,0,0.22,0.0
2021-05-10 00:00:00-04:00,123.761185,126.385678,123.722158,126.258853,88071200,0.00,0.0
2021-05-11 00:00:00-04:00,122.844086,123.195313,119.780538,120.492766,126142800,0.00,0.0
2021-05-12 00:00:00-04:00,119.780556,121.605024,119.273221,120.395220,112172300,0.00,0.0
2021-05-13 00:00:00-04:00,121.926994,123.078262,121.234284,121.546491,105861300,0.00,0.0
...,...,...,...,...,...,...,...
2026-05-01 00:00:00-04:00,280.140015,287.220001,278.369995,278.859985,79915400,0.00,0.0
2026-05-04 00:00:00-04:00,276.829987,280.630005,274.859985,279.660004,46668400,0.00,0.0
2026-05-05 00:00:00-04:00,284.179993,284.570007,276.500000,276.929993,49311700,0.00,0.0
2026-05-06 00:00:00-04:00,287.510010,288.029999,281.070007,281.920013,58336100,0.00,0.0
2026-05-07 00:00:00-04:00,287.440002,292.130005,285.779999,289.269989,45145500,0.00,0.0

In [ ]:
prix_triés=prix.drop_duplicates().dropna()
prix_triés

In [ ]:
prix_triés.dtypes

Open            float64
High            float64
Low             float64
Close           float64
Volume            int64
Dividends       float64
Stock Splits    float64
dtype: object

In [ ]:
incohérences=prix_triés[prix_triés["Low"]>prix_triés["High"]]
incohérences

Empty DataFrame
Columns: [Open, High, Low, Close, Volume, Dividends, Stock Splits]
Index: []

In [ ]:
prix_triés_vn=prix_triés[prix_triés["Volume"]==0]
prix_triés_vn

Empty DataFrame
Columns: [Open, High, Low, Close, Volume, Dividends, Stock Splits]
Index: []

Calcul du rendement journalier:

In [ ]:
prix_triés["rendement journalier"]=prix_triés["Close"].pct_change()*100
prix_triés

,Open,High,Low,Close,Volume,Dividends,Stock Splits,rendement,rendement journalier
Date,,,,,,,,,
2021-05-03 00:00:00-04:00,128.606386,130.583611,128.401855,129.093384,75135100,0.00,0.0,NaN,NaN
2021-05-04 00:00:00-04:00,127.778479,128.070680,123.405233,124.525330,137564700,0.00,0.0,-3.538566,-3.538566
2021-05-05 00:00:00-04:00,125.840223,127.057718,124.642213,124.768837,84000900,0.00,0.0,0.195548,0.195548
2021-05-06 00:00:00-04:00,124.564313,126.375946,123.824074,126.366211,78128300,0.00,0.0,1.280267,1.280267
2021-05-07 00:00:00-04:00,127.663814,128.063819,126.327163,127.039398,78973300,0.22,0.0,0.532727,0.532727
...,...,...,...,...,...,...,...,...,...
2026-04-27 00:00:00-04:00,266.089996,268.359985,265.070007,267.609985,41466800,0.00,0.0,-1.272785,-1.272785
2026-04-28 00:00:00-04:00,272.339996,273.230011,268.660004,270.709991,40018900,0.00,0.0,1.158404,1.158404
2026-04-29 00:00:00-04:00,267.549988,271.040009,267.040009,270.170013,30047900,0.00,0.0,-0.199467,-0.199467
2026-04-30 00:00:00-04:00,270.500000,276.000000,268.140015,271.350006,91848200,0.00,0.0,0.436759,0.436759
2026-05-01 00:00:00-04:00,278.859985,287.220001,278.369995,280.140015,79844600,0.00,0.0,3.239362,3.239362

In [ ]:
pt=prix_triés
rdm_max=round(pt['rendement journalier'].max(), 2)
volume_correspondant=pt[pt['rendement journalier']==pt['rendement journalier'].max()]
print("le rendement journalier maximal est",rdm_max,"%")

le rendement journalier maximal est 15.33 %

In [ ]:
ptdj=pt.tail(90)
ptdj['rendement journalier'].mean()*100

np.float64(3.854358273608162)

In [ ]:
display(pt.tail(100))

In [ ]:
moyenne_rdm=pt["rendement journalier"].mean()*100
moyenne_rdm

np.float64(7.6697668132610985)

In [ ]:
volume_correspondant

,Open,High,Low,Close,Volume,Dividends,Stock Splits,rendement,rendement journalier
Date,,,,,,,,,
2025-04-09 00:00:00-04:00,171.203815,199.739448,171.144078,197.987091,184395900,0.0,0.0,15.328859,15.328859

**REMARQUE:**
Après calcul du rendement journalier de l'actif AAPL(Apple), le rendement maximal depuis le 03 Avril 2021 à nos jour est de 15,33% precisement au 09 Mars 2025 avec un volume de **184395900**.Nous obtenons en moyenne sur les **90 derniers jours** un rendement journalier de ***3,85%***.